version: "3.9"

services:
  app:
    build: .
    ports:
      - "7236:7236"
    volumes:
      - ./server:/app/server
    command: npm run server
    environment:
      - NODE_ENV=production
    restart: unless-stopped