version: "3.9"

services:
  app:
    build: .
    ports:
      - "7236:7236"
    volumes:
      - ./server:/app/server
    command: npm run server
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 7236 || exit 1"]
      interval: 30s
      timeout: 10s